import StyleSheet from 'react-native-extended-stylesheet';
// import {ifIphoneX} from 'react-native-iphone-x-helper';

export default StyleSheet.create({
  Bullish: {
    color: '#17C491',
    backgroundColor: 'rgba(23, 196, 145, 0.2)',
    fontFamily: 'SFProDisplay-Medium',
    textTransform: 'capitalize',
    fontSize: 16,
    letterSpacing: 0.1,
    paddingHorizontal: 2,
  },
  Bearish: {
    color: '#FC3E30',
    backgroundColor: 'rgba(252, 62, 48, 0.2)',
    fontFamily: 'SFProDisplay-Medium',
    textTransform: 'capitalize',
    fontSize: 16,
    letterSpacing: 0.1,
    paddingHorizontal: 2,
  },
  Yolo: {
    color: '#0e141e',
    fontFamily: 'SFProDisplay-Medium',
    backgroundColor: 'rgba(252, 199, 59, 0.7)',
    fontSize: 16,
    letterSpacing: 0.1,
    paddingHorizontal: 2,
  },
  Loss: {
    color: '#0e141e',
    fontFamily: 'SFProDisplay-Medium',
    backgroundColor: 'rgba(252, 62, 48, 0.7)',
    textTransform: 'capitalize',
    fontSize: 16,
    letterSpacing: 0.1,
    paddingHorizontal: 2,
  },
  Gain: {
    color: '#0e141e',
    fontFamily: 'SFProDisplay-Medium',
    backgroundColor: 'rgba(23, 196, 145, 0.7)',
    textTransform: 'capitalize',
    fontSize: 16,
    letterSpacing: 0.1,
    paddingHorizontal: 2,
  },
  Shitpost: {
    color: '#0e141e',
    fontFamily: 'SFProDisplay-Medium',
    backgroundColor: 'rgba(139, 87, 42, 0.7)',
    textTransform: 'capitalize',
    fontSize: 16,
    letterSpacing: 0.1,
    paddingHorizontal: 2,
  },
  Stocks: {
    color: '#0e141e',
    fontFamily: 'SFProDisplay-Medium',
    backgroundColor: 'rgba(16, 115, 240, 0.7)',
    textTransform: 'capitalize',
    fontSize: 16,
    letterSpacing: 0.1,
    paddingHorizontal: 2,
  },
  Options: {
    color: '#0e141e',
    fontFamily: 'SFProDisplay-Medium',
    backgroundColor: 'rgba(109, 98, 229, 0.7)',
    textTransform: 'capitalize',
    fontSize: 16,
    letterSpacing: 0.1,
    paddingHorizontal: 2,
  },
  Cryptos: {
    color: '#0e141e',
    fontFamily: 'SFProDisplay-Medium',
    backgroundColor: 'rgba(255, 74, 0, 0.7)',
    textTransform: 'capitalize',
    fontSize: 16,
    letterSpacing: 0.1,
    paddingHorizontal: 2,
  },
  Discussion: {
    color: '#0e141e',
    fontFamily: 'SFProDisplay-Medium',
    backgroundColor: 'rgba(39, 156, 211, 0.7)',
    textTransform: 'capitalize',
    fontSize: 16,
    letterSpacing: 0.1,
    paddingHorizontal: 2,
  },
  Futures: {
    color: '#0e141e',
    fontFamily: 'SFProDisplay-Medium',
    backgroundColor: 'rgba(255, 96, 126, 0.7)',
    textTransform: 'capitalize',
    fontSize: 16,
    letterSpacing: 0.1,
    paddingHorizontal: 2,
  },
  Satire: {
    color: '#0e141e',
    fontFamily: 'SFProDisplay-Medium',
    backgroundColor: 'rgba(142, 142, 147, 0.7)',
    textTransform: 'capitalize',
    fontSize: 16,
    letterSpacing: 0.1,
    paddingHorizontal: 2,
  },
  Shrug: {
    color: '#0e141e',
    fontFamily: 'SFProDisplay-BoldItalic',
    textTransform: 'capitalize',
    fontSize: 16,
    letterSpacing: 0.1,
  },
});
