import {CHANGE_THEME_REQUEST} from '../actions/themeManager';
import Platform from 'react-native';

const initialState = {
  light: {
    primaryBackgroundColor: '#FFFF',
    secondaryBackgroundColor: '#F6F7F9',
    primaryTextColor: '#0E141E',
    secondaryTextColor: '#585C63',
    placeholderTextColor: '#8E8E93',
    tiltGreen: '#17C491',
    tiltRed: '#FC3E30',
    buttonTextColor: '#FFF',
    borderBottomColor: '#DCDCDC',
    mediaBorderColor: '#DCDCDC',
    headerTintColor: '#0E141E',
    emojiReactionsBackgroundColor: '#F6F7F9',
    emojiReactionsBorderBackgroundColor: '#D9D8D7',
    threadSeparatorColor: '#EBEBEB',
    intervalSelectedTextColor: '#FFF',
    intervalUnselectedTextColor: '#17C491',
    intervalSelectedBackgroundColor: '#17C491',
    intervalUnselectedBackgroundColor: '#FFF',
    modalPopupBackgroundColor: '#FFF',
    codeBackgroundColor: '#F4F4F4',
    userMentionBackgroundColor: '#E4EFFF',
    joinButtonBackgroundColor: '#EBEBEB',
    jumpToHighlightColor: '#FCF4DD',
    barStyleColor: 'dark-content',
    keyboardAppearanceColor: 'light',
    segmentedControlBackgroundColor: 'rgba(118, 118, 128, 0.12)',
  },
  dark: {
    primaryBackgroundColor: '#040D14',
    secondaryBackgroundColor: '#0E141E',
    primaryTextColor: '#FFFF',
    secondaryTextColor: '#585C63',
    placeholderTextColor: '#8E8E93',
    tiltGreen: '#17C491',
    tiltRed: '#FC3E30',
    buttonTextColor: '#040D14',
    borderBottomColor: '#353942',
    mediaBorderColor: '#353942',
    headerTintColor: '#FFF',
    emojiReactionsBackgroundColor: '#1e242e',
    emojiReactionsBorderBackgroundColor: '#1e242e',
    threadSeparatorColor: '#1e242e',
    intervalSelectedTextColor: '#0E141E',
    intervalUnselectedTextColor: '#17C491',
    intervalSelectedBackgroundColor: '#17C491',
    intervalUnselectedBackgroundColor: '#040D14',
    modalPopupBackgroundColor: '#0E141E',
    codeBackgroundColor: 'rgba(244,244,244,0.1)',
    userMentionBackgroundColor: 'rgba(228,239,255,0.2)',
    joinButtonBackgroundColor: 'rgba(235,235,235,0.1)',
    jumpToHighlightColor: 'rgba(252,244,221,0.2)',
    barStyleColor: 'light-content',
    keyboardAppearanceColor: 'dark',
    segmentedControlBackgroundColor: 'rgba(118, 118, 128, 0.24)',
  },
  darkGray: {
    primaryBackgroundColor: '#262A2F',
    secondaryBackgroundColor: '#2D3239',
    primaryTextColor: '#FFFF',
    secondaryTextColor: '#585C63',
    placeholderTextColor: '#8E8E93',
    tiltGreen: '#17C491',
    tiltRed: '#FC3E30',
    buttonTextColor: '#262A2F',
    borderBottomColor: '#0E141E',
    mediaBorderColor: '#0E141E',
    headerTintColor: '#FFF',
    emojiReactionsBackgroundColor: '#1E242E',
    emojiReactionsBorderBackgroundColor: '#1E242E',
    threadSeparatorColor: '#2D3239',
    intervalSelectedTextColor: '#2D3239',
    intervalUnselectedTextColor: '#17C491',
    intervalSelectedBackgroundColor: '#17C491',
    intervalUnselectedBackgroundColor: '#262A2F',
    modalPopupBackgroundColor: '#2D3239',
    codeBackgroundColor: 'rgba(244,244,244,0.1)',
    userMentionBackgroundColor: 'rgba(228,239,255,0.2)',
    joinButtonBackgroundColor: 'rgba(235,235,235,0.1)',
    jumpToHighlightColor: 'rgba(252,244,221,0.2)',
    barStyleColor: 'light-content',
    keyboardAppearanceColor: 'dark',
    segmentedControlBackgroundColor: 'rgba(118, 118, 128, 0.24)',
  },
  current: 'light',
  entities: ['light', 'darkGray', 'dark'],
  displayNames: ['Light', 'Dark Gray', 'Midnight'],
};

const themeReducer = (state = initialState, action) => {
  switch (action.type) {
    case CHANGE_THEME_REQUEST:
      return {
        ...state,
        current: action.payload,
      };
    default:
      return state;
  }
};

export default themeReducer;
